Vagrant.configure("2") do |config|
  config.vm.define "linux_vm" do |linux|
    linux.vm.box = "generic/ubuntu2004" 
    linux.vm.provider "qemu" do |qemu|
      qemu.memory = 1024 
      qemu.cpus = 2      
    end
  end

  config.vm.define "windows_vm" do |windows|
    windows.vm.box = "gusztavvargadr/windows-10"
    windows.vm.provider "qemu" do |qemu|
      qemu.memory = 2048
      qemu.cpus = 2
    end
  end

  config.vm.define "mac_vm" do |mac|
    mac.vm.box = "macos-catalina"
    mac.vm.provider "qemu" do |qemu|
      qemu.memory = 2048
      qemu.cpus = 2
    end
  end
end

